# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  - compiler: ": #Linux"
    addons: {apt: {packages: [libgmp,libgmp-dev]}}
  - compiler: ": #OS X"
    os: osx

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Get the stack executable on the PATH
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

# Make sure we can run our program
script:
- ./FileServer.hs sanity
